name: CompatibilityPlugin
version: 1.0.7
author: Neovitalism
main: me.neovitalism.compatibilityplugin.CompatibilityPlugin
description: A plugin that brings Pixelmon Compatibility to other plugins.
api-version: 1.20

softdepend: [BattlePass,NeoExtras,OldSchoolBreeding]